config/routes.rb
Rails.application.routes.draw do
  resources :cryptos
  devise_for :users
  root 'cryptos#index'
  get 'home/about'
  get 'home/lookup'
  post '/home/lookup' => 'home/lookup'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/crypto.rb
class Crypto < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cryptos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cryptos_controller.rb
class CryptosController < ApplicationController
  before_action :set_crypto, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :correct_user, only: %i[ show edit update destroy ]

  # GET /cryptos or /cryptos.json
  def index
    @cryptos = Crypto.all
    require 'net/http'
    require 'json'
    #require 'coingecko_ruby'
    require 'cryptocompare'
    @tickers = ["BTC", "ETH", "XRP"]
    @symbol = params[:sym]
    if @symbol
      @symbol = @symbol.upcase
    end
    if @symbol == ""
      @symbol = "Type your symbol!"
    end
  end

  # GET /cryptos/1 or /cryptos/1.json
  def show
  end

  # GET /cryptos/new
  def new
    @crypto = Crypto.new
  end

  # GET /cryptos/1/edit
  def edit
  end

  # POST /cryptos or /cryptos.json
  def create
    @crypto = Crypto.new(crypto_params)

    respond_to do |format|
      if @crypto.save
        format.html { redirect_to crypto_url(@crypto), notice: "Crypto was successfully created." }
        format.json { render :show, status: :created, location: @crypto }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @crypto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cryptos/1 or /cryptos/1.json
  def update
    respond_to do |format|
      if @crypto.update(crypto_params)
        format.html { redirect_to crypto_url(@crypto), notice: "Crypto was successfully updated." }
        format.json { render :show, status: :ok, location: @crypto }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @crypto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cryptos/1 or /cryptos/1.json
  def destroy
    @crypto.destroy

    respond_to do |format|
      format.html { redirect_to cryptos_url, notice: "Crypto was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crypto
      @crypto = Crypto.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def crypto_params
      params.require(:crypto).permit(:symbol, :user_id, :cost_per, :amount_owned)
    end

    def correct_user
      @correct = current_user.cryptos.find_by(id: params[:id])
      redirect_to cryptos_path, notice: "Not authorized to edit this." if @correct.nil?
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    require 'net/http'
    require 'json'
    #require 'coingecko_ruby'
    require 'cryptocompare'

    #@url = 'https://pro-api.coinmarketcap.com/v1/cryptocurrency/map?CMC_PRO_API_KEY=6ac2d474-e89c-4ae2-8f1d-c44ffa0850c5'
    #@uri = URI(@url)
    #@response = Net::HTTP.get(@uri)
    #@coins = JSON.parse(@response)
    #@client = CoingeckoRuby::Client.new
    @client = Cryptocompare::Price.find('ETH', 'USD', { api_key: 'API_KEY' })
    @tickers = ["BTC", "ETH", "XRP"]
  end

  def about
  end

  def lookup
    require 'net/http'
    require 'json'
    #require 'coingecko_ruby'
    require 'cryptocompare'
    @tickers = ["BTC", "ETH", "XRP"]

    @symbol = params[:sym]
    if @symbol
      @symbol = @symbol.upcase
    end
    if @symbol == ""
      @symbol = "Type your symbol!"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cryptos_helper.rb
module CryptosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/cryptos/_form.html.erb
<%= form_with(model: crypto) do |form| %>
  <% if crypto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(crypto.errors.count, "error") %> prohibited this crypto from being saved:</h2>

      <ul>
        <% crypto.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :symbol %>
    <%= form.text_field :symbol %>
  </div>

  <div class="field">
    <%= form.number_field :user_id, value: current_user.id, type: "hidden" %>
  </div>

  <div class="field">
    <%= form.label :cost_per %>
    <%= form.text_field :cost_per %>
  </div>

  <div class="field">
    <%= form.label :amount_owned %>
    <%= form.text_field :amount_owned %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cryptos/edit.html.erb
<h1>Editing Crypto</h1>

<%= render 'form', crypto: @crypto %>

<%= link_to 'Show', @crypto %> |
<%= link_to 'Back', cryptos_path %>

app/views/cryptos/index.html.erb
<% profit_loss = 0 %>

<h1>Cryptos</h1>
<br>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Symbol</th>
      <th>Cost per Coin</th>
      <th>Market price</th>
      <th>Amount owned</th>
      <th>Current Value</th>
      <th>Profit/Loss</th>
    </tr>
  </thead>
  <tbody>
    <% @cryptos.each do |crypto| %>
     <% if crypto.user_id == current_user.id %>
      <tr>
          <td><%= link_to Cryptocompare::Price.full(crypto.symbol.upcase, 'USD', { api_key: 'API_KEY' })["RAW"][crypto.symbol.upcase]["USD"]["FROMSYMBOL"], crypto %></td>
          <td>$<%= crypto.cost_per %></td>
          <td>$<%= Cryptocompare::Price.find(crypto.symbol.upcase, 'USD', { api_key: 'API_KEY' })[crypto.symbol.upcase]["USD"] %></td>
          <td><%= crypto.amount_owned %></td>
          <td>$<%= (Cryptocompare::Price.find(crypto.symbol.upcase, 'USD', { api_key: 'API_KEY' })[crypto.symbol.upcase]["USD"] * crypto.amount_owned) %></td>
          <td><%= ((Cryptocompare::Price.find(crypto.symbol.upcase, 'USD', { api_key: 'API_KEY' })[crypto.symbol.upcase]["USD"] * crypto.amount_owned) - (crypto.cost_per * crypto.amount_owned)) %></td>
          <td><% profit_loss += ((Cryptocompare::Price.find(crypto.symbol.upcase, 'USD', { api_key: 'API_KEY' })[crypto.symbol.upcase]["USD"] * crypto.amount_owned) - (crypto.cost_per * crypto.amount_owned)) %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<br>

<strong>Portfolio Profit/Loss:  </strong><%= number_to_currency(profit_loss) %>
<br><br>
<%= link_to 'New Crypto', new_crypto_path, class: "btn btn-default" %>

app/views/cryptos/new.html.erb
<h1>New Crypto</h1>

<%= render 'form', crypto: @crypto %>

<%= link_to 'Back', cryptos_path %>

app/views/cryptos/show.html.erb
<p>
  <strong>Symbol:</strong>
  <%= @crypto.symbol %>
</p>

<p>
  <strong>User:</strong>
  <%= @crypto.user_id %>
</p>

<p>
  <strong>Cost per:</strong>
  <%= @crypto.cost_per %>
</p>

<p>
  <strong>Amount owned:</strong>
  <%= @crypto.amount_owned %>
</p>

<%= link_to 'Edit', edit_crypto_path(@crypto) %> |
<%= link_to 'Back', cryptos_path %>
<%= link_to 'Destroy', crypto_path(@crypto), method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/home/_flash.html.erb
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

<% flash.each do |name, msg| %>
  <div class="alert alert-warning alert-dismissible">
    <button class="close" data-dismiss= "alert">
      <i class="glyphicon glyphicon-remove-circle"></i>
    </button>
    <%= content_tag(:div, msg) %>
  </div>
<% end %>

app/views/home/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "My Portfolio", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Search Crypto", home_lookup_path %></li>
        <% if user_signed_in? %>
        <li><%= link_to "Add Crypto", new_crypto_path %></li>
          <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
          <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>

        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Log In", new_user_session_path %></li>
        <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/home/index.html.erb
<%# <h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<% require 'cryptocompare' %>

app/views/home/lookup.html.erb
<% require 'cryptocompare' %>
<h3>Look for your Cryptocurrency</h3>
<%= form_tag home_lookup_path, :method => 'POST' do %>
  <%= text_field_tag 'sym', nil, placeholder: 'Enter Crypto Symbol', size: 50 %>
  <%= submit_tag 'Lookup Crypto' %>
<% end %>

<div class= "result">
  <% if @tickers.include? @symbol%>
      <% @price = Cryptocompare::Price.find(@symbol, 'USD', { api_key: 'API_KEY' }) %>
      <% @coin = Cryptocompare::Price.full(@symbol, 'USD') %>
      <%= @coin["RAW"][@symbol]["USD"]["FROMSYMBOL"] %>: <%= @price[@symbol]["USD"] %><br>
    <% else %>
      <%= "" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CryptoPortfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

  </head>

  <body>
    <%= render 'home/navbar' %>

    <div class="container">
      <%= render 'home/flash' %>
      <%= yield %>
    </div>
  </body>
</html>